// menuData.js
export const combosData = [
  { id: 1, combo_name: 'Combo 1', name: '1 - Panceta/ Torresmo/ Carne Seca/ Linguiça Mineira/ Queijo/ Aipim', price: 150.00, description: 'Serve 6 pessoas' },
  { id: 2, combo_name: 'Combo 2', name: '2 - Panceta/ Torresmo/ Carne Seca/ Linguica Mineira/ Aipim', price: 130.00, description: 'Serve 5 pessoas' },
  { id: 3, combo_name: 'Combo 3', name: '3 - Panceta/ Torresmo/ Carne Seca/ Aipim', price: 120.00, description: 'Serve 4 pessoas' },
  { id: 4, combo_name: 'Combo 4', name: '4 - Panceta/ Carne Seca/ Aipim', price: 100.00, description: 'Serve 4 pessoas' },
  { id: 5, combo_name: 'Combo 5', name: '5 - Torresmo/ Carne Seca/ Aipim', price: 90.00, description: 'Serve 4 pessoas' },
  { id: 6, combo_name: 'Combo 6', name: '6 - Panceta/ Torresmo/ Aipim', price: 75.00, description: 'Serve 3 pessoas' },
];

export const porcoesSeparadasData = [
  { id: 1, name: 'Carne seca com aipim', price: 70.00, description: '' },
  { id: 2, name: 'Contrá filé com fritas', price: 70.00, description: '' },
  { id: 3, name: 'Panceta com aipim', price: 60.00, description: '' },
  { id: 4, name: 'Torresmo com aipim', price: 50.00, description: '' },
  { id: 5, name: 'Linguiça com aipim', price: 40.00, description: '' },
  { id: 6, name: 'Batata frita', price: 30.00, description: '' },
  { id: 7, name: 'Porção de aipim', price: 30.00, description: '' },
  { id: 8, name: 'Coxinha de frango empanado sem pimenta', price: 40.00, description: 'Contem 10 unidades' },
  { id: 9, name: 'Coxinha de frango empanado com pimenta', price: 40.00, description: 'Contem 10 unidades' },
  { id: 10, name: 'Salame', price: 20.00, description: '' },
  { id: 11, name: 'Queijo coalho', price: 10.00, description: '100g' },
  { id: 12, name: 'Gurjão de peixe', price: 60.00, description: '' },
];

export const meiaPorcao = [
  { id: 1, name: 'Meia porção de torresmo', price: 30.00, description: '' },
  { id: 2, name: 'Meia porção de panceta', price: 40.00, description: '' },
  { id: 3, name: 'Meia porção de carne seca', price: 50.00, description: '' },
  { id: 4, name: 'Meia porção de linguiça', price: 20.00, description: '' },
];

export const churrascoNoPalito = [
  { id: 1, name: 'Churrasquinho Misto', price: 10.00, description: 'Unidade' },
  { id: 1, name: 'Churrasquinho de Carne', price: 10.00, description: 'Unidade' },
];

export const cerveja = [
  { id: 1, name: 'ANTARTICA', price: 10.00, description: '600ml' },
  { id: 2, name: 'BRAHMA', price: 10.00, description: '600ml' },
  { id: 3, name: 'BUDWEISER', price: 10.00, description: '600ml' },
  { id: 4, name: 'BOHEMIA', price: 10.00, description: '600ml' },
  { id: 5, name: 'BRAHMA DUPLO MALTE', price: 11.00, description: '600ml' },
  { id: 6, name: 'ORIGINAL', price: 13.00, description: '600ml' },
  { id: 7, name: 'SPATEN', price: 13.00, description: '600ml' },
  { id: 8, name: 'STELLA', price: 14.00, description: '600ml' },
  { id: 9, name: 'BECKS', price: 15.00, description: '600ml' },
  { id: 10, name: 'CORONA', price: 15.00, description: '600ml' },
  { id: 11, name: 'BUDWEISER', price: 8.00, description: 'LONG NECK' },
  { id: 12, name: 'BUDWEISER ZERO ALCOOL', price: 8.00, description: 'LONG NECK' },
  { id: 13, name: 'BRAHMA ZERO ALCOOL', price: 8.00, description: 'LONG NECK' },
  { id: 14, name: 'SPATEN', price: 9.00, description: 'LONG NECK' },
  { id: 15, name: 'MALZEBIER', price: 9.00, description: 'LONG NECK' },
  { id: 16, name: 'STELLA', price: 10.00, description: 'LONG NECK' },
  { id: 17, name: 'STELLA PURE GOLD', price: 10.50, description: 'LONG NECK' },
  { id: 18, name: 'CORONA', price: 11.00, description: 'LONG NECK' },
  { id: 19, name: 'CORONA ZERO ALCOOL', price: 12.00, description: 'LONG NECK' },
];

export const refrigerante = [
  { id: 1, name: 'GUARANÁ ANTARTICA', price: 7.00, description: 'LATA' },
  { id: 2, name: 'GUARANÁ ANTARTICA ZERO', price: 7.00, description: 'LATA' },
  { id: 3, name: 'PEPSI', price: 7.00, description: 'LATA' },
  { id: 4, name: 'PEPSI BLACK', price: 7.00, description: 'LATA' },
  { id: 5, name: 'COCA COLA KS', price: 6.00, description: '290ml' },
  { id: 6, name: 'COCA COLA', price: 8.00, description: 'LATA' },
  { id: 7, name: 'COCA COLA', price: 15.00, description: '2L' },
  { id: 8, name: 'TÔNICA', price: 7.00, description: '' },
  { id: 9, name: 'H20H ', price: 8.00, description: '500ml' },
  { id: 10, name: 'GATORADE', price: 8.00, description: '' },
  { id: 11, name: 'ÁGUA SEM GÁS ', price: 5.00, description: '500ml' },
  { id: 12, name: 'ÁGUA COM GÁS ', price: 5.00, description: '500ml' },
  { id: 13, name: 'RED BULL ', price: 12.00, description: '250ml' },
  { id: 14, name: 'GUARAVITA ', price: 3.00, description: '' },
  { id: 15, name: 'SUCO ', price: 8.00, description: 'LATA' },
  { id: 16, name: 'SPRITE ', price: 7.00, description: 'LATA' },
  { id: 17, name: 'MATTE ', price: 12.00, description: '1,5L' },
  { id: 18, name: 'SUCO  ', price: 12.00, description: '1L' },
  { id: 19, name: 'COCA COLA', price: 9.00, description: '600ML' },
  { id: 20, name: 'ENERGETICO', price: 10.00, description: '' },
]

export const doses = [
  { id: 1, name: 'BEATS', price: 10.00, description: 'LONG NECK' },
  { id: 2, name: 'SMIRNOFF ICE', price: 10.00, description: 'LONG NECK' },
  { id: 3, name: 'CACHAÇA SELETA', price: 8.00, description: 'DOSE' },
  { id: 4, name: 'CACHAÇA SALINA', price: 8.00, description: 'DOSE' },
  { id: 5, name: 'CACHAÇA MINEIRA', price: 5.00, description: 'DOSE' },
  { id: 6, name: 'CACHAÇA MARULA', price: 8.00, description: 'DOSE' },
  { id: 7, name: 'CACHAÇA BANANINHA', price: 7.00, description: 'DOSE' },
  { id: 8, name: 'CACHAÇA DREHER', price: 7.00, description: 'DOSE' },
  { id: 9, name: 'CACHAÇA VELHO BARREIRO', price: 5.00, description: 'DOSE' },
  { id: 10, name: 'CACHAÇA DOMECQ', price: 8.00, description: 'DOSE' },
  { id: 11, name: 'CACHAÇA PARATUDO', price: 7.00, description: 'DOSE' },
  { id: 12, name: 'CACHAÇA STEINHAGER', price: 8.00, description: 'DOSE' },
  { id: 13, name: 'CACHAÇA 51', price: 5.00, description: 'DOSE' },
  { id: 14, name: 'CACHAÇA MEL', price: 6.00, description: 'DOSE' },
  { id: 15, name: 'CACHAÇA CONHAQUE DE ALCATRÃO', price: 7.00, description: 'DOSE' },
  { id: 16, name: 'CACHAÇA YPIOCA AMARELA', price: 7.00, description: 'DOSE' },
  { id: 17, name: 'CACHAÇA YPIOCA COM PALHA', price: 8.00, description: 'DOSE' },
  { id: 18, name: 'CACHAÇA CABARÉ', price: 8.00, description: 'DOSE' },
  { id: 19, name: 'CACHAÇA BACARDI', price: 15.00, description: 'DOSE' },
  { id: 20, name: 'GIN + ÁGUA TÔNICA', price: 25.00, description: 'DOSE' },
  { id: 21, name: 'WHISKY RED LABEL', price: 25.00, description: 'DOSE' },
  { id: 22, name: 'WHISKY RED LABEL BLACK', price: 30.00, description: 'DOSE' },
  { id: 23, name: 'CAVALO BRANCO', price: 20.00, description: 'DOSE' },
  { id: 24, name: 'CAIPIRINHA COMUM', price: 15.00, description: '350ml' },
  { id: 25, name: 'CAIPIRINHA SELETA', price: 20.00, description: '350ml' },
  { id: 26, name: 'CAIPIRINHA VELHO BARREIRO', price: 15.00, description: '350ml' },
  { id: 27, name: 'CAIPIVODKA', price: 20.00, description: '350ml' },
  { id: 28, name: 'VODKA', price: 12.00, description: 'DOSE' },
  { id: 29, name: 'LICOR 43', price: 25.00, description: 'DOSE' },
  { id: 30, name: 'LICOR 43', price: 180.00, description: 'GARRAFA' },
  { id: 31, name: 'CHOPP DE VINHO', price: 12.00, description: 'GARRAFA' },
  { id: 32, name: 'VINHO', price: 12.00, description: 'TAÇA' },
  { id: 33, name: 'TORO CABERNET SAUVIGNON', price: 60.00, description: 'GARRAFA' },
  { id: 34, name: 'VINHO SECO', price: 35.00, description: 'GARRAFA' },
]

export const doces = [
  { id: 1, name: 'Doce', price: 3.00, description: 'unidade' },
]

export const sorvetes = [
  { id: 1, name: 'Chocoblitz', price: 7.90, description: '' },
  { id: 2, name: 'Chocoblitz black', price: 7.90, description: '' },
  { id: 3, name: 'Start', price: 7.90, description: '' },
  { id: 4, name: 'Leitinho com Avella', price: 6.90, description: '' },
  { id: 5, name: 'Chocotella', price: 6.90, description: '' },
  { id: 6, name: 'Chocolate com Coco', price: 6.90, description: '' },
  { id: 7, name: 'Brigadeiro', price: 6.90, description: '' },
  { id: 8, name: 'Tentação', price: 6.90, description: '' },
  { id: 9, name: 'Gold Bem Casado', price: 11.90, description: '' },
  { id: 10, name: 'Gold Torta Holandesa', price: 11.90, description: '' },
  { id: 11, name: 'Speciale Toffee', price: 9.90, description: '' },
  { id: 12, name: 'Speciale Petit Gateau', price: 9.90, description: '' },
  { id: 13, name: 'Speciale Torta de Limão', price: 9.90, description: '' },
  { id: 14, name: 'Speciale Choqquito', price: 9.90, description: '' },
  { id: 15, name: 'Speciale ', price: 9.90, description: '' },
  { id: 16, name: 'Leitinho Trufado', price: 11.90, description: '' },
  { id: 17, name: 'Banoffee', price: 11.90, description: '' },
  { id: 18, name: 'Copão', price: 7.90, description: '' },
  { id: 19, name: 'Sunday', price: 6.50, description: '' },
  { id: 20, name: 'Caixa bombom', price: 12.90, description: '' },
  { id: 21, name: 'Pote Luigi', price: 13.90, description: '500ml' },
  { id: 22, name: 'Zero açucar de Coco', price: 6.00, description: '' },
  { id: 23, name: 'Pote Luigi zero açucar', price: 14.90, description: '' },
  { id: 24, name: 'Paleta leitinho trufado', price: 9.90, description: '' },
  { id: 25, name: 'Paleta Morando com leite condensado', price: 9.90, description: '' },
  { id: 26, name: 'Paleta Paçoquinha', price: 9.90, description: '' },
  { id: 27, name: 'Cremoso Chocolate', price: 4.50, description: '' },
  { id: 28, name: 'Cremoso Coco', price: 4.50, description: '' },
  { id: 29, name: 'Fazenda Morango', price: 4.50, description: '' },
  { id: 30, name: 'Fazenda Milho', price: 4.50, description: '' },
  { id: 31, name: 'Fazenda Doce de Leite', price: 4.50, description: '' },
  { id: 32, name: 'Frutas Açai', price: 4.00, description: '' },
  { id: 33, name: 'Frutas Maracujá', price: 4.00, description: '' },
  { id: 34, name: 'Frutas Uva', price: 4.00, description: '' },
  { id: 35, name: 'Frutas Limão', price: 4.00, description: '' },
  { id: 36, name: 'Smile', price: 4.00, description: '' },
  { id: 37, name: 'Chiclete', price: 3.00, description: '' },
  { id: 38, name: 'Unicornio', price: 4.50, description: '' },
  { id: 39, name: 'Dino', price: 6.00, description: '' },
  { id: 40, name: 'Brigalove', price: 5.50, description: '' },
  { id: 41, name: 'Moranguinho', price: 4.50, description: '' },
  { id: 42, name: 'Grego ', price: 9.90, description: '' },
]

export const pf = [
  { id: 1, name: 'PF Contra File com Fritas', price: 35.00, description: 'Prato Feito' },
  { id: 2, name: 'PF Carne Seca', price: 25.00, description: 'Prato Feito' },
  { id: 3, name: 'PF File de Frango', price: 25.00, description: 'Prato Feito' },
  { id: 4, name: 'PF Carré', price: 25.00, description: 'Prato Feito' },
  { id: 5, name: 'PF Linguiça Mineira', price: 25.00, description: 'Prato Feito' },
  { id: 6, name: 'Guarnição', price: 20.00, description: '' },
  { id: 7, name: 'Arroz', price: 10.00, description: '' },
  { id: 8, name: 'Feijão', price: 5.00, description: '' },
  { id: 9, name: 'Salada', price: 7.00, description: '' },
]

export const outros = [
  { id: 1, name: 'PIRAQUE', price: 6.00, description: 'BISCOITO' },
  { id: 2, name: 'GOIABINHA', price: 5.00, description: 'BISCOITO' },
  { id: 3, name: 'RITINHA', price: 5.00, description: 'BISCOITO' },
  { id: 4, name: 'POLVILHO GRANDE', price: 10.00, description: 'BISCOITO' },
  { id: 5, name: 'CARLTON', price: 12.00, description: 'CIGARRO' },
  { id: 6, name: 'LUCKY STRIKE', price: 8.00, description: 'CIGARRO' },
  { id: 7, name: 'ROTHMANS', price: 7.50, description: 'CIGARRO' },
]
